In [1]:
!pip install --upgrade scipy pandas opencv-python

  Using cached scipy-1.15.2-cp312-cp312-win_amd64.whl.metadata (60 kB)
  Using cached opencv_python-4.11.0.86-cp37-abi3-win_amd64.whl.metadata (20 kB)
   ---------------------------------------- 0.0/40.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/40.9 MB ? eta -:--:--
    --------------------------------------- 0.5/40.9 MB 1.4 MB/s eta 0:00:29
    --------------------------------------- 0.8/40.9 MB 1.3 MB/s eta 0:00:32
   - -------------------------------------- 1.0/40.9 MB 1.3 MB/s eta 0:00:31
   - -------------------------------------- 1.3/40.9 MB 1.3 MB/s eta 0:00:31
   - -------------------------------------- 1.6/40.9 MB 1.3 MB/s eta 0:00:31
   - -------------------------------------- 1.8/40.9 MB 1.3 MB/s eta 0:00:31
   -- ------------------------------------- 2.1/40.9 MB 1.3 MB/s eta 0:00:31
   -- ------------------------------------- 2.4/40.9 MB 1.3 MB/s eta 0:00:30
   -- ------------------------------------- 2.6/40.9 MB 1.3 MB/s eta 0:00:30
   -- ----------

  You can safely remove it manually.
  You can safely remove it manually.


In [2]:
import pandas as pd
data = pd.read_csv("IMDBDataset.csv")
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer()

docs = np.array(['The sun is shining',
               'The weather is sweet',
               'The sun is shining, the weather is sweet, and one and one is two'])

bag = count.fit_transform(docs)

In [4]:
print(count.vocabulary_)

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 8, 'sweet': 5, 'and': 0, 'one': 2, 'two': 7}


In [5]:
print(bag.toarray())

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]
